import { test, expect, Page } from '@playwright/test';

const MOCK_MARKET_ID = 'mock-market';

test('guest can explore dashboard and open a market', async ({ page }) => {
  await mockApi(page);

  await page.goto('/');
  await expect(
    page.getByRole('heading', { name: /Polymarket intelligence/i })
  ).toBeVisible();

  await page.getByRole('button', { name: /Explore without wallet/i }).click();
  await expect(
    page.getByRole('heading', { name: /Trending markets/i })
  ).toBeVisible();

  await page.getByRole('link', { name: 'Mock Market' }).click();
  await page.waitForURL('**/market/mock-market');
  await expect(page.getByRole('heading', { name: 'Mock Market' })).toBeVisible();
  await expect(
    page.getByText('Mock summary generated by tests.')
  ).toBeVisible();
});

async function mockApi(page: Page) {
  const insightPayload = {
    success: true,
    data: {
      dateKey: '2025-11-19',
      generatedAt: new Date().toISOString(),
      model: 'qwen',
      cadence: 'daily',
      sections: [
        {
          heading: 'Crypto',
          confidence: 0.72,
          items: [{ title: 'BTC range', summary: 'Bitcoin ranging', topic: 'crypto' }],
        },
      ],
    },
  };

  const marketSummary = {
    id: MOCK_MARKET_ID,
    title: 'Mock Market',
    category: 'Crypto',
    topics: ['crypto'],
    status: 'open',
    yesProbability: 0.42,
    yesPrice: 0.42,
    change24h: 0.05,
    volume24h: 12500,
    totalVolume: 240000,
    liquidity: 80000,
    isHot: true,
    isSpike: false,
    polymarketUrl: 'https://polymarket.com/event/mock',
    updatedAt: new Date().toISOString(),
  };

  const marketDetail = {
    ...marketSummary,
    description: 'Mock description',
    priceSeries: [
      { timestamp: new Date().toISOString(), value: 0.42 },
      { timestamp: new Date(Date.now() - 86_400_000).toISOString(), value: 0.38 },
    ],
    volumeSeries: [
      { timestamp: new Date().toISOString(), value: 1200 },
      { timestamp: new Date(Date.now() - 86_400_000).toISOString(), value: 900 },
    ],
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  };

  await page.route('**/api/insights/daily**', (route) => {
    route.fulfill({ json: insightPayload });
  });

  await page.route('**/api/insights/daily/sections', (route) => {
    route.fulfill({ json: insightPayload });
  });

  await page.route('**/api/markets?**', (route) => {
    route.fulfill({
      json: { success: true, data: { items: [marketSummary] } },
    });
  });

  await page.route(`**/api/markets/${MOCK_MARKET_ID}`, (route) => {
    route.fulfill({ json: { success: true, data: marketDetail } });
  });

  await page.route(`**/api/markets/${MOCK_MARKET_ID}/summary`, (route) => {
    route.fulfill({
      json: {
        success: true,
        data: { summary: 'Mock summary generated by tests.', generatedAt: new Date().toISOString() },
      },
    });
  });
}
